name: Build Gatsby

# Controls when the action will run.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

    - name: Install dependencies & build
      run: |
        npm ci
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./public
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Percy for Static Sites
      uses: percy/snapshot-action@v0.1.2
#       with:
#         # The directory where your static site outputs its build to
#         build-directory: # optional, default is 
#         # CLI flags to pass to `percy snapshot`
#         flags: # optional, default is 
#         # The working directory which the commands should be executed in
#         working-directory: # optional, default is ./
#         # Silence logging
#         silence: # optional
#         # Enable verbose logging
#         verbose: # optional
      env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
